# Example configuration file for self-calibration pipeline
# Copy this file and modify the parameters as needed for your specific use case

# Container images
container_images:
  linc: "astronrd/linc:latest"      # Single container with DP3 and wsclean
  dp3: "astronrd/linc:latest"       # Use linc for DP3 operations
  wsclean: "astronrd/linc:latest"   # Use linc for wsclean operations

# Self-calibration parameters
selfcal_params:
  iterations: 5                      # Increase iterations for better convergence
  smoothness_constraint: 0.05       # Tighter constraint for smoother solutions
  solver_type: "LBFGS"              # Solver type: LBFGS, CG, or SVD
  max_iterations: 200               # More iterations for solver
  tolerance: 1.0e-4                 # Stricter convergence tolerance
  solution_interval: 0              # Solution interval (0 = per scan)
  use_model_data: true              # Use MODEL_DATA column for calibration
  model_column: "MODEL_DATA"        # Name of model column (filled by wsclean)

# Imaging parameters for wsclean
imaging_params:
  image_size: [8192, 8192]          # Higher resolution image
  pixel_scale: "1arcmin"            # Finer pixel scale
  weighting: "briggs"               # Weighting scheme: uniform, natural, briggs
  briggs_robust: 0.0                # More natural weighting
  clean_iterations: 1000            # More clean iterations
  mgain: 0.8                        # Lower gain for more stable convergence
  multiscale: true                  # Enable multiscale cleaning
  auto_threshold: true              # Enable auto threshold
  auto_mask: true                   # Enable auto mask
  mem_percentage: 90                # Use more memory
  enable_prediction: true           # Enable prediction mode for self-calibration

# DP3 calibration parameters
dp3_params:
  ntime: 2                          # Process more time slots
  write_full_res_flag: true         # Write full resolution flags
  apply_smooth: true                # Apply smoothing to solutions
  use_model_column: true            # Use model column for calibration
  model_column: "MODEL_DATA"        # Name of model column (filled by wsclean)
  calibration_type: "gain"          # Calibration type: gain, phase, or bandpass
  solution_interval: 0              # Solution interval (0 = per scan)

# Output configuration
output_config:
  base_output_dir: "./high_res_selfcal_output"
  save_intermediate: true           # Save intermediate results
  save_parsets: true                # Save DP3 parset files
  save_logs: true                   # Save detailed logs
  generate_report: true             # Generate JSON report
  save_model_images: true           # Save model images for each iteration

# Performance tuning
performance_config:
  parallel_processing: true         # Enable parallel processing if available
  memory_limit: "90%"               # Higher memory limit for containers
  cpu_limit: "all"                  # CPU limit for containers
  timeout: 7200                     # Longer timeout for high-resolution processing

# Quality control thresholds
quality_thresholds:
  min_snr: 5.0                      # Higher SNR requirement
  max_gain_error: 0.3               # Stricter gain error limit
  min_solutions: 0.9                # Require more successful solutions
  convergence_threshold: 1.0e-4     # Stricter convergence threshold
  model_data_quality: true          # Check quality of MODEL_DATA column

# Logging configuration
logging_config:
  default_level: "DEBUG"
  file_level: "DEBUG"
  console_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: "200MB"
  backup_count: 10
